"""add publication year to book

Revision ID: 307ebcd3cf8f
Revises: 1e102d59182a
Create Date: 2026-04-06 14:47:09.985931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307ebcd3cf8f'
down_revision: Union[str, Sequence[str], None] = '1e102d59182a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'publication_year')
    # ### end Alembic commands ###
